[tool.poetry]
name = "supername"
version = "0.1.0"
description = "supername project"
authors = ["trbouma <trbouma@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.4"
typer = "^0.12.0"
secp256k1 = "^0.14.0"
loguru = "^0.7.2"
bolt11 = "^2.0.5"
bip32 = "^3.4"
requests = "^2.31.0"
python-dotenv = "^1.0.1"
psycopg2 = "^2.9.9"

[tool.poetry.scripts]
supername = "supername.main:main"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


