[tool.poetry]
name = "supername"
version = "0.1.0"
description = "supername project"
authors = ["trbouma <trbouma@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.4"
fastapi = "^0.110.0"
typer = "^0.12.0"
secp256k1 = "^0.14.0"
sqlalchemy = "^2.0.29"
loguru = "^0.7.2"
httpx = "^0.27.0"
bolt11 = "^2.0.5"
bip32 = "^3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
